// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5Su9Zn-K7TfauGrSUrcOY3lAHtN-fRnA',
    appId: '1:675045068250:web:8ea5970d1c5f5f3872c4e3',
    messagingSenderId: '675045068250',
    projectId: 'parent-pal-f9258',
    authDomain: 'parent-pal-f9258.firebaseapp.com',
    storageBucket: 'parent-pal-f9258.appspot.com',
    measurementId: 'G-HXYQJM06HC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyyfPXxs0t5oP1bzymK7CyNVVutloRlDA',
    appId: '1:675045068250:android:aefec85adb5499ba72c4e3',
    messagingSenderId: '675045068250',
    projectId: 'parent-pal-f9258',
    storageBucket: 'parent-pal-f9258.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDmoCBFO7FdJGtFbEsqKg90GQOU_816-U',
    appId: '1:675045068250:ios:c2c51f07ce778be972c4e3',
    messagingSenderId: '675045068250',
    projectId: 'parent-pal-f9258',
    storageBucket: 'parent-pal-f9258.appspot.com',
    iosBundleId: 'com.parentpal.parentPal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDmoCBFO7FdJGtFbEsqKg90GQOU_816-U',
    appId: '1:675045068250:ios:c2c51f07ce778be972c4e3',
    messagingSenderId: '675045068250',
    projectId: 'parent-pal-f9258',
    storageBucket: 'parent-pal-f9258.appspot.com',
    iosBundleId: 'com.parentpal.parentPal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5Su9Zn-K7TfauGrSUrcOY3lAHtN-fRnA',
    appId: '1:675045068250:web:d9dc59322014ee0c72c4e3',
    messagingSenderId: '675045068250',
    projectId: 'parent-pal-f9258',
    authDomain: 'parent-pal-f9258.firebaseapp.com',
    storageBucket: 'parent-pal-f9258.appspot.com',
    measurementId: 'G-XKRSWMHCMF',
  );
}
